matrix:
  include:
    - language: node_js
      node_js:
        - 12
      install:
        - cd server && npm install && cd ..
      script:
        - cd server && npm test
    - language: swift
      osx_image: xcode11
      script:
        # - set -o pipefail
        - cd app && cd pets && xcodebuild build -project pets.xcodeproj -scheme "pets" -sdk iphonesimulator | xcpretty
        # - cd app && cd pets && xcodebuild test -project pets.xcodeproj -scheme pets -destination "platform=iOS Simulator,OS=13,name=iPhone 11 Pro" test | xcpretty

notifications:
  email:
    - matheusgoislimasilva@gmail.com 