matrix:
  include:
    - language: node_js
    node_js:
      - 12
    install:
      - cd server && npm install && cd ..
    script:
      - cd server && npm test
    - language: swift
      osx_image: xcode11
      script:
      - cd app && cd pets &&  - xcodebuild -scheme pets -sdk pets -destination 'platform=iOS Simulator,name=iPhone X Pro,OS=13' build test

notifications:
  email:
    - matheusgoislimasilva@gmail.com