matrix:
  include:
    - language: node_js
    node_js:
      - 12
    install:
      - cd server && npm install && cd ..
    script:
      - cd server && npm test
    - language: swift
      osx_image: xcode11
      script:
      - cd app && cd pets && xcodebuild test -project pets.xcodeproj -scheme pets -destination "platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro Max" test | xcpretty

notifications:
  email:
    - matheusgoislimasilva@gmail.com