# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
    - run: cd server
    - run: npm i
    - run: npm run build --if-present
    - run: npm run coverage
    - name: wget
      uses: wei/wget@v1
      with:
        args: -qO- https://coverage.codacy.com/get.sh | sh -s report -l Javascript -r coverage/lcov.info
