name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.2,name=iPhone 11 Pro Max']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: cd app
        run: cd app && cd pets
      - name: Build and test part 1
        run:  xcodebuild clean test -project pets.xcodeproj -scheme pets -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      - name: Build and test part 2
        run:  bash <(curl -s https://codecov.io/bash)
        env: 
         destination: ${{ matrix.destination }}
